import{i as c,S as d}from"./assets/vendor-5ObWk2rO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const u="46873247-b56a65fb4c08f29194ce1856e",f="https://pixabay.com/api/";async function m(a,r=1,o=12){const n=`${f}?key=${u}&q=${encodeURIComponent(a)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${o}&page=${r}`;try{const e=await fetch(n);if(!e.ok)throw new Error("Failed to fetch images");return await e.json()}catch(e){throw c.error({title:"Error",message:"Failed to fetch images from Pixabay API"}),e}}function g(a){const r=document.getElementById("gallary");r.innerHTML=a.map(({webformatURL:o,largImageURL:n,tags:e,likes:t,views:s,comments:l,dowloads:E})=>`<a href="${largeImageURL}" class="gallery-item">
          <img src="${o}" alt="${e}" />
          <div class="info">
            <p>Likes: ${t}</p>
            <p>Views: ${s}</p>
            <p>Comments: ${l}</p>
            <p>Downloads: ${downloads}</p>
          </div>
        </a>`).join(""),new d(".gallery a",{captionsData:"alt",captionDelay:250})}function p(){document.getElementById("loader").classList.remove("hidden")}function y(){document.getElementById("loader").classList.add("hidden")}function h(){c.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"})}let i=1;const L=document.getElementById("search-form"),w=document.getElementById("gallery");L.addEventListener("submit",async a=>{a.preventDefault();const r=a.target.elements.query.value.trim();if(r){i=1,w.innerHTML="",p();try{const o=await m(r,i);if(o.hits.length===0){h();return}g(o.hits)}catch(o){console.error("Error fetching images:",o)}finally{y()}}});
//# sourceMappingURL=index.js.map
