import{i as a,S as u}from"./assets/vendor-5ObWk2rO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const p="46873247-b56a65fb4c08f29194ce1856e",h="https://pixabay.com/api/";async function y(s,r=1,o=15){const i=`${h}?key=${p}&q=${encodeURIComponent(s)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${o}&page=${r}`;try{console.log("Fetching URL:",i);const e=await fetch(i);if(!e.ok)throw new Error("Failed to fetch images");const t=await e.json();return t.hits.length===0&&a.info({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"16",backgroundColor:"#ef4040",messageColor:"#fafafb",maxWidth:"432px",messageLineHeight:"88px"}),t}catch(e){throw a.error({position:"topRight",message:"Failed to fetch images from Pixabay API",backgroundColor:"#ef4040",messageColor:"#fafafb"}),e}}function b(s){const r=document.getElementById("gallery"),o=s.map(({webformatURL:e,largeImageURL:t,tags:n,likes:f,views:m,comments:d,downloads:g})=>`
    <a href="${t}" class="gallery-item">
      <img src="${e}" alt="${n}" />
      <div class="info">
        <p>Likes: ${f}</p>
        <p>Views: ${m}</p>
        <p>Comments: ${d}</p>
        <p>Downloads: ${g}</p>
      </div>
    </a>
  `).join("");r.innerHTML=o,new u(".gallery-item").refresh()}const c=document.getElementById("search-form"),L=document.getElementById("gallery"),l=document.getElementById("loader");c.addEventListener("submit",async s=>{s.preventDefault();const r=c.elements.query.value.trim();if(r===""){iziToast.warning({title:"Warning",message:"Please enter a search query."});return}L.innerHTML="",l.classList.remove("hidden");try{const o=await y(r);b(o.hits)}catch(o){console.error("Error fetching images:",o)}finally{l.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
